# Generated by Django 5.2 on 2025-04-08 17:07

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cave',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cave',
            name='longitude',
        ),
        migrations.AddField(
            model_name='cave',
            name='address',
            field=models.CharField(default='123 memory lane', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cave',
            name='city',
            field=models.CharField(default='Springfield', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cave',
            name='state',
            field=localflavor.us.models.USStateField(default='IL', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cave',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
    ]
