# Generated by Django 5.2 on 2025-04-09 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_cave_latitude_remove_cave_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cave',
            name='rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='sleeps',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.CreateModel(
            name='Hibernation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('nights', models.IntegerField(validators=[django.core.validators.MaxValueValidator(90)])),
                ('bear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cave')),
            ],
        ),
    ]
