# Generated by Django 5.2 on 2025-04-09 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_cave_rate_alter_cave_sleeps_hibernation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hibernation',
            name='nights',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hibernation',
            name='start_date',
            field=models.DateField(verbose_name='First night'),
        ),
    ]
