# Generated by Django 5.2 on 2025-04-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_hibernation_nights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('cave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cave')),
            ],
        ),
    ]
