# Generated by Django 5.2 on 2025-04-10 19:59

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_hibernation_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.filepath),
        ),
    ]
